# Generated by Django 4.2.4 on 2023-09-07 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateField(verbose_name=datetime.datetime(2023, 9, 7, 21, 19, 24, 137165)),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateField(verbose_name=datetime.datetime(2023, 9, 7, 21, 19, 24, 137165)),
        ),
    ]
