# Generated by Django 4.2.4 on 2023-09-07 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_room_created_alter_room_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='created',
            field=models.DateField(default=datetime.datetime(2023, 9, 7, 21, 31, 46, 861848)),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated',
            field=models.DateField(default=datetime.datetime(2023, 9, 7, 21, 31, 46, 861848)),
        ),
    ]
